spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://monimal:monimal123@monimal.bv37www.mongodb.net/fashion_chatbot_db?retryWrites=true&w=majority&appName=Monimal}

chatbot:
  security:
    allow-direct-user-header: false

ai:
  log-requests: false
  log-responses: false
