server:
  port: 8086

spring:
  data:
    mongodb:
      # Cấu hình cụ thể nằm trong review-service-dev.yml hoặc review-service-prod.yml


review:
  integration:
    order-service-url: ${ORDER_SERVICE_URL:http://localhost:8084}
    promotion-service-url: ${PROMOTION_SERVICE_URL:http://localhost:8085}
