spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8888"

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:${EMAIL_USERNAME:pcshop7153@gmail.com}}
    password: ${SPRING_MAIL_PASSWORD:${EMAIL_PASSWORD:tvpwqiovicyfkbfq}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  auth:
    email-verification-required: ${EMAIL_VERIFICATION_REQUIRED:true}
