spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8888"

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:${MAIL_USERNAME:your-email@gmail.com}}
    password: ${SPRING_MAIL_PASSWORD:${MAIL_PASSWORD:your-app-password}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
