server:
  port: 8086

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/fashion_review_db}
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:CHANGE_ME_base64_encoded_secret_key_at_least_32_bytes}
